### ISSUE TITLE
Correction Docs

### ISSUE THREAD

**Issue by marota** [marota/ExpertOp4Grid#29]
![image](https://user-images.githubusercontent.com/5496312/94433336-708ede00-0198-11eb-930b-23f14d0f2109.png)
Typo, ça n'affiche pas en "code"

**Comment by NMegel** [comment]
Done in commit 876401971d719421620ef2bfbba0d2731b3816b8 (and added missing images in DESCRIPTION chapter)

**Comment by NMegel** [comment]
Handling capital letters in images extension: fc208d42be14b1dd05ef63b4246508b25687f941

**Comment by marota** [comment]
@NMegel @mjothy 

![image](https://user-images.githubusercontent.com/5496312/94547838-1fdabc00-0250-11eb-9e9d-6bb4f38e9ba0.png)
Rendre lisible les dataframes (sur fond noir) dans https://github.com/marota/ExpertOp4Grid/blob/master/docs/DETAILS.rst

**Comment by mjothy** [comment]
@marota Tu as une idée particulière ? Actuellement si on clique sur l'image, elle est beaucoup plus grosse et plus lisible, donc ça m'avait l'air suffisant. Tu souhaites qu'on refasse l'image avec des charactères plus gros ?

**Comment by marota** [comment]
@mjothy dans readthedocs, on ne peut pas "cliquer" sur l'image, à moins que j'ai loupé un truc... donc on ne voit rien. L'idée serait d'agrandir l'image de la dataframe sur toute la largeur ici, et de la mettre sur un fond type tableur excel pour mieux la lire, en particulier le nom des colonnes. Et enlever le commentaire "comme pypownet le recrache) :)

**Comment by marota** [comment]
Même chose ici: 
![image](https://user-images.githubusercontent.com/5496312/94918835-ac38e900-04b3-11eb-86d9-923ff514da81.png)

Pour le fond, préférer un fond clair plus lisible ici

**Comment by mjothy** [comment]
done in
25199014788b971e2a12feb91da21dd731778031
908ab0245c0d77ae211ad73758be1e3dc4cf1c4d
