### ISSUE TITLE
In Grid2opSimulator.cut_line_and_recompute_flow, adding timestep=0 to simulate breaks 2 integration tests

### ISSUE THREAD

**Issue by NMegel** [marota/ExpertOp4Grid#33]
To avoid problems with forecasted chronics, I changed code in Grid2opSimulator.cut_lines_and_recomputes_flows

from

obs_linecut, reward, done, info = self.obs.simulate(deconexion_action,)

to

obs_linecut, reward, done, info = self.obs.simulate(deconexion_action, time_step = 0)

It breaks 2 integration tests

![image](https://user-images.githubusercontent.com/35769324/102360110-e6456180-3fb1-11eb-8908-f6c36689e882.png)

* In test test_integration_dataframe_results_with_case_14_realistic, 2 topos are subsituted in the dataframe. Moreover, there are very slight differences in topology score.

* In test test_integration_dataframe_results_no_hubs, it should be an empty dataframe because no electric hubs are detected. But now a full dataframe is returned with hubs

**Comment by NMegel** [comment]
Pour no_hubs, je propose de faire porter le test sur
- grid = "l2rpn_2019"
- chronic = i
- timestep = 1
ce qui donne effectivement un dataframe vide après modification de time_step=0

**Comment by marota** [comment]
@NMegel Ok ça me paraît approprié. Peux-tu juste poster les dataframe avant et après pour se rendre compte des différences des topos qui apparaissent/disparaissent ?

**Comment by NMegel** [comment]
Voici les dataframe avant et après pour le test case_14_realistic
Tu verras qu'il y a 2 topologies qui changent (numéro 15 et 16 dans les dataframes)
[test_integration_dataframe_results_with_case_14_realistic.zip](https://github.com/marota/ExpertOp4Grid/files/5830562/test_integration_dataframe_results_with_case_14_realistic.zip)
Tu valides que je modifie le test?

Pour l'autre test, je change juste les paramètres comme proposé pour obtenir un dataframe vide!

**Comment by NMegel** [comment]
Après ces modifications, tous les tests passent (commit 61e88eecd332eda13eb04f2c7e501576557cec5a)
![image](https://user-images.githubusercontent.com/35769324/105194184-9bcb7d80-5b39-11eb-958a-94567c7efc25.png)

**Comment by NMegel** [comment]
Previous .zip appeared to be empty
[test_integration_dataframe_results_with_case_14_realistic.zip](https://github.com/marota/ExpertOp4Grid/files/5873916/test_integration_dataframe_results_with_case_14_realistic.zip)
